stages:
  -test
  -build

run_tests:
  stage:test
  image: jenkins: jdk11
  before_script:
    - sudo apt-get update && sudo apt-get install make
  script:
    - make test

build_test:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $ -p $
  script:
    - docker build -t abirami0107:v1
    - docker push abirami0107/spring:v1


  
